CREATE DATABASE IF NOT EXISTS auto_sy DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE auto_sy;

CREATE TABLE IF NOT EXISTS tb_auto_watchlist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(30) NOT NULL,
  exchange VARCHAR(8) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tb_auto_watchlist_symbol (symbol)
);

CREATE TABLE IF NOT EXISTS tb_auto_position (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(30) NOT NULL,
  quantity INT NOT NULL,
  avg_price DOUBLE NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tb_auto_position_symbol (symbol)
);

CREATE TABLE IF NOT EXISTS tb_auto_order_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(30) NOT NULL,
  side VARCHAR(10) NOT NULL,
  quantity INT NOT NULL,
  price DOUBLE NOT NULL,
  reason VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_auto_price_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(30) NOT NULL,
  price DOUBLE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_auto_strategy (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(30) NOT NULL,
  strategy_type VARCHAR(100),
  status VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
